name: Build and Push Docker Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/bockwurstboy/backupr
          tags: |
            type=raw,value=latest
            type=sha,prefix=sha-

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Cleanup untagged images
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: |
          REPO="ghcr.io/bockwurstboy/backupr"
          untagged_sha=$(curl -s -H "Authorization: Bearer $GHCR_PAT" \
            "https://ghcr.io/v2/${REPO}/tags/list" | jq -r '.tags[] | select(startswith("sha256:"))')
          for sha in ${untagged_sha}; do
            echo "Deleting untagged image: ${sha}"
            digest=$(curl -s -I -H "Authorization: Bearer $GHCR_PAT" \
              "https://ghcr.io/v2/${REPO}/manifests/${sha}" | awk '$1 == "Docker-Content-Digest:" { print $2 }' | tr -d $'\r')
            curl -X DELETE -H "Authorization: Bearer $GHCR_PAT" \
              "https://ghcr.io/v2/${REPO}/manifests/${digest}"
          done
